class HomeController < ApplicationController
  def index
    @countries = [
      ["Antigua and Barbuda", "AG"],
      ["Argentina", "AR"],
      ["Aruba", "AW"],
      ["Australia", "AU"],
      ["Austria", "AT"],
      ["Bahamas", "BS"],
      ["Bahrain", "BH"],
      ["Bangladesh", "BD"],
      ["Barbados", "BB"],
      ["Belgium", "BE"],
      ["Belize", "BZ"],
      ["Bermuda", "BM"],
      ["Bolivia", "BO"],
      ["Bosnia and Herzegowina", "BA"],
      ["Botswana", "BW"],
      ["Brazil", "BR"],
      ["British Virgin Islands", "VG"],
      ["Bulgaria", "BG"],
      ["Burkina Faso", "BF"],
      ["Cambodia", "KH"],
      ["Canada", "CA"],
      ["Cayman Islands", "KY"],
      ["Chile", "CL"],
      ["China", "CN"],
      ["Colombia", "CO"],
      ["Costa Rica", "CR"],
      ["Croatia", "HR"],
      ["Cuba", "CU"],
      ["Curacao", "CW"],
      ["Cyprus", "CY"],
      ["Czech Republic", "CZ"],
      ["Denmark", "DK"],
      ["Dominica", "DM"],
      ["Dominican Republic", "DO"],
      ["Ecuador", "EC"],
      ["Egypt", "EG"],
      ["Estonia", "EE"],
      ["Ethiopia", "ET"],
      ["Fiji", "FJ"],
      ["Finland", "FI"],
      ["France", "FR"],
      ["Germany", "DE"],
      ["Ghana", "GH"],
      ["Greece", "GR"],
      ["Greenland", "GL"],
      ["Grenada", "GD"],
      ["Guatemala", "GT"],
      ["Honduras", "HN"],
      ["Hong Kong", "HK"],
      ["Hungary", "HU"],
      ["Iceland", "IS"],
      ["India", "IN"],
      ["Indonesia", "ID"],
      ["Ireland", "IE"],
      ["Israel", "IL"],
      ["Italy", "IT"],
      ["Jamaica", "JM"],
      ["Japan", "JP"],
      ["Jordan", "JO"],
      ["Kenya", "KE"],
      ["Laos", "LA"],
      ["Latvia", "LV"],
      ["Lebanon", "LB"],
      ["Lesotho", "LS"],
      ["Lithuania", "LT"],
      ["Luxembourg", "LU"],
      ["Macao", "MO"],
      ["Madagascar", "MG"],
      ["Malawi", "MW"],
      ["Malaysia", "MY"],
      ["Mali", "ML"],
      ["Malta", "MT"],
      ["Mauritania", "MR"],
      ["Mexico", "MX"],
      ["Micronesia", "FM"],
      ["Monaco", "MC"],
      ["Mongolia", "MN"],
      ["Morocco", "MA"],
      ["Mozambique", "MZ"],
      ["Myanmar", "MM"],
      ["Namibia", "NA"],
      ["Nepal", "NP"],
      ["Netherlands", "NL"],
      ["New Zealand", "NZ"],
      ["Nicaragua", "NI"],
      ["Norway", "NO"],
      ["Panama", "PA"],
      ["Papua New Guinea", "PG"],
      ["Paraguay", "PY"],
      ["Peru", "PE"],
      ["Philippines", "PH"],
      ["Poland", "PL"],
      ["Portugal", "PT"],
      ["Puerto Rico", "PR"],
      ["Qatar", "QA"],
      ["Romania", "RO"],
      ["Russia", "RU"],
      ["Rwanda", "RW"],
      ["Saint Barthelemy", "BL"],
      ["Saint Kitts and Nevis", "KN"],
      ["Saint Lucia", "LC"],
      ["Senegal", "SN"],
      ["Serbia", "RS"],
      ["Singapore", "SG"],
      ["Slovakia", "SK"],
      ["Slovenia", "SI"],
      ["Solomon Islands", "SB"],
      ["South Africa", "ZA"],
      ["South Korea", "KR"],
      ["Spain", "ES"],
      ["Sri Lanka", "LK"],
      ["Swaziland", "SZ"],
      ["Sweden", "SE"],
      ["Switzerland", "CH"],
      ["Taiwan", "TW"],
      ["Tanzania", "TZ"],
      ["Thailand", "TH"],
      ["Turkey", "TR"],
      ["Turks and Caicos Islands", "TC"],
      ["Uganda", "UG"],
      ["Ukraine", "UA"],
      ["United Arab Emirates", "AE"],
      ["United Kingdom", "GB"],
      ["United States of America", "US"],
      ["Uruguay", "UY"],
      ["US Virgin Islands", "VI"],
      ["Vanautu", "VU"],
      ["Vietnam", "VN"],
      ["Zambia", "ZM"],
      ["Zimbabwe", "ZW"]
    ]
  end
end
